apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    receivers:
      {{- toYaml .Values.config.receivers | nindent 6 }}
    
    processors:
      {{- toYaml .Values.config.processors | nindent 6 }}
    
    exporters:
      {{- toYaml .Values.config.exporters | nindent 6 }}
    
    extensions:
      {{- toYaml .Values.config.extensions | nindent 6 }}
    
    service:
      {{- toYaml .Values.config.service | nindent 6 }}
